name: "UnitreeGo2"
config:
  urdf_path: "urdf/urdf/go2_description.urdf"
  class_dir: "unitree_go_2"
  network_interface: "enx000ec6bdee34"       # (Optional) Network interface to use
  frequency: 240  # default is 240Hz
  width: 0.31   # Width of the robot (m)
  control: "joint_space"
  joint_space_control:
    Kp: 60.0               # Joint stiffness coefficient
    Kd: 5.0                # Joint damping coefficient
  odometry: False
  show_odometry: False
  show_frequency: 30
  contact_force_threshold: 20.0
  initial_configuration:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0